<a href="https://colab.research.google.com/github/jiyakaushik26/Data-science/blob/main/day-6(pandas).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Pandas**

**Pandas** is a Python library used for working with data sets.


It has functions for **analyzing, cleaning, exploring, and manipulating data.**

In [ ]:
import pandas as pd

In [ ]:
file= pd.read_csv('./student_data.csv')
print(file)

      study_hours  attendance  sleep_hours  internet_usage  \
0               7          56            8               7
1               4          69            5               3
2              11          60            7               6
3               8          99            9               8
4               5          52            8               6
...           ...         ...          ...             ...
9995            2          58            9               7
9996            7          98            6               9
9997           10          44            8               5
9998           10          75            7               5
9999            2          70            6              11

      assignments_completed  previous_score  exam_score placement_status
0                        10              62      100.00           Placed
1                         8              56      100.00           Placed
2                        10              45      100.00           Placed
3                         4              55       90.17           Placed
4                         8              40       78.82           Placed
...                     ...             ...         ...              ...
9995                      8              88       69.31       Not Placed
9996                      4              87      100.00           Placed
9997                     10              37       95.94           Placed
9998                      8              52       88.61           Placed
9999                     16              52       78.96           Placed

[10000 rows x 8 columns]

**seperator-> sep(' ')->** helps to seperate the data

Head-> gives the initial n rows passed in head(n)

In [ ]:
file1=pd.read_csv('./student_data.csv', sep=',')
print(file1.head(8))

   study_hours  attendance  sleep_hours  internet_usage  \
0            7          56            8               7
1            4          69            5               3
2           11          60            7               6
3            8          99            9               8
4            5          52            8               6
5            7          40            9              10
6           10          40            4              11
7            3          86            7               3

   assignments_completed  previous_score  exam_score placement_status
0                     10              62      100.00           Placed
1                      8              56      100.00           Placed
2                     10              45      100.00           Placed
3                      4              55       90.17           Placed
4                      8              40       78.82           Placed
5                      0              60       72.33           Placed
6                      9              50       98.12           Placed
7                      7              85      100.00           Placed

A Pandas **DataFrame** is a two-dimensional, size-mutable, and potentially heterogeneous tabular data structure with labeled axes (rows and columns)

df is a DataFrame object

**pd.DataFrame(...)** is a Pandas function that converts data into a table.

display(df)-> Shows a prettier table with proper row/column formatting.

we can also write simply df to print the data

pd.DataFrame(file) = convert file → table

In [ ]:
dct={
    'name':['Ton', 'Krish', 'Vani', 'Jiya'],
    'age':[20,11,18,19],
    'roll': [1,2,3,4]
}
df=pd.DataFrame(dct)
df

display(df)

    name  age  roll
0    Ton   20     1
1  Krish   11     2
2   Vani   18     3
3   Jiya   19     4

**To change the index**

In [ ]:
dct={
    'name':['Ton', 'Krish', 'Vani', 'Jiya'],
    'age':[20,11,18,19],
    'roll': [1,2,3,4]
}
df=pd.DataFrame(dct, index=['a','b','c','d'])
df

    name  age  roll
a    Ton   20     1
b  Krish   11     2
c   Vani   18     3
d   Jiya   19     4

**df.head(n)->** Show the first n rows of the DataFrame.

In [ ]:
df=pd.read_csv('student_data.csv')
df.head(3)

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.0,Placed
1,4,69,5,3,8,56,100.0,Placed
2,11,60,7,6,10,45,100.0,Placed

**df.tail(n)->** Show the last n rows of the DataFrame.

In [ ]:
df=pd.read_csv('student_data.csv')
df.tail(3)

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
9997,10,44,8,5,10,37,95.94,Placed
9998,10,75,7,5,8,52,88.61,Placed
9999,2,70,6,11,16,52,78.96,Placed

**df.shape-> ** df.shape tells you the size of the DataFrame

In [ ]:
df=pd.read_csv('student_data.csv')
df.shape

(10000, 8)

We have read json and etc as read csv

Metadata-data about data

**df.info()** gives a summary of the DataFrame or the metadata

In [ ]:
df=pd.read_csv('student_data.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   study_hours            10000 non-null  int64
 1   attendance             10000 non-null  int64
 2   sleep_hours            10000 non-null  int64
 3   internet_usage         10000 non-null  int64
 4   assignments_completed  10000 non-null  int64
 5   previous_score         10000 non-null  int64
 6   exam_score             10000 non-null  float64
 7   placement_status       10000 non-null  object
dtypes: float64(1), int64(6), object(1)
memory usage: 625.1+ KB

**df.describe()->** gives a statistical summary of the numeric columns in your DataFrame

q1, q2, q3-> quartiles

q1-> median from start till median of entire line(25%)

q3-> median from last till median of entire line(75%)

q2-> median  of entire line(50%)

In [ ]:
df=pd.read_csv('student_data.csv')
df.describe()

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score
count,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000
mean,5.989600,69.88460,6.498500,6.062600,9.988400,64.91100,86.704207
std,3.163589,17.61653,1.709354,3.138163,6.034145,17.50302,15.058383
min,1.000000,40.00000,4.000000,1.000000,0.000000,35.00000,26.670000
25%,3.000000,55.00000,5.000000,3.000000,5.000000,50.00000,76.727500
50%,6.000000,70.00000,6.500000,6.000000,10.000000,65.00000,92.120000
75%,9.000000,85.00000,8.000000,9.000000,15.000000,80.00000,100.000000
max,11.000000,100.00000,9.000000,11.000000,20.000000,95.00000,100.000000

**df.columns->** gives the list of columns by name

In [ ]:
df=pd.read_csv('student_data.csv')
df.columns

Index(['study_hours', 'attendance', 'sleep_hours', 'internet_usage',
       'assignments_completed', 'previous_score', 'exam_score',
       'placement_status'],
      dtype='object')

**df.index->** gives the range of data from where it starts and ends and whats the step

In [ ]:
df=pd.read_csv('student_data.csv')
df.index

RangeIndex(start=0, stop=10000, step=1)

In [ ]:
df=pd.read_csv('student_data.csv')
df['internet_usage']

0        7
1        3
2        6
3        8
4        6
        ..
9995     7
9996     9
9997     5
9998     5
9999    11
Name: internet_usage, Length: 10000, dtype: int64

**Returns only these columns from the DataFrame use->**

Avoid using df.dataframe and use brackets and if u want to pass a list write **df.[[]]**

In [ ]:
df=pd.read_csv('student_data.csv')
df[['internet_usage', 'study_hours']]

      internet_usage  study_hours
0                  7            7
1                  3            4
2                  6           11
3                  8            8
4                  6            5
...              ...          ...
9995               7            2
9996               9            7
9997               5           10
9998               5           10
9999              11            2

[10000 rows x 2 columns]

**iloc[n]->** uses to access the nth row information

In [ ]:
df=pd.read_csv('student_data.csv')
df.iloc[0]

study_hours                   7
attendance                   56
sleep_hours                   8
internet_usage                7
assignments_completed        10
previous_score               62
exam_score                100.0
placement_status         Placed
Name: 0, dtype: object

you can also find the range of info of rows from m to n by **iloc[m:n]**

In [ ]:
df=pd.read_csv('student_data.csv')
df.iloc[0:5]

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.00,Placed
1,4,69,5,3,8,56,100.00,Placed
2,11,60,7,6,10,45,100.00,Placed
3,8,99,9,8,4,55,90.17,Placed
4,5,52,8,6,8,40,78.82,Placed

To get filtered data->

use **df.loc(what you want)**

df.loc is a Pandas accessor used to select data from a DataFrame by row labels and column names.

In [ ]:
df=pd.read_csv('student_data.csv')
df.loc[df['study_hours']==11]

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
2,11,60,7,6,10,45,100.00,Placed
9,11,77,4,9,15,69,100.00,Placed
10,11,64,8,8,12,76,100.00,Placed
29,11,63,9,10,1,72,96.59,Placed
30,11,45,5,2,4,93,100.00,Placed
...,...,...,...,...,...,...,...,...
9969,11,84,8,2,3,83,100.00,Placed
9971,11,81,9,6,0,85,100.00,Placed
9978,11,92,8,2,16,79,100.00,Placed
9979,11,78,9,5,18,82,100.00,Placed
9988,11,94,6,9,6,67,100.00,Placed

**df.loc[df['study_hours']==11, ['study_hours', 'sleep_hours']].iloc[4:8]**->

"Find all students whose study_hours equals 11, keep only the study_hours and sleep_hours columns, then show the 5th through 8th matching rows."

**iloc** access data through index only

**loc** access data through labels

iloc apni indexing or kaam krta hai

In [ ]:
df=pd.read_csv('student_data.csv')
df.loc[df['study_hours']==11, ['study_hours', 'sleep_hours']].iloc[4:8]

     study_hours  sleep_hours
30            11            5
91            11            9
98            11            6
116           11            7

In [ ]:
df=pd.read_csv('student_data.csv')
df2=df.loc[df['study_hours']==11]
df2.iloc[4:8]

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
30,11,45,5,2,4,93,100.0,Placed
91,11,100,9,4,6,43,100.0,Placed
98,11,100,6,9,2,74,100.0,Placed
116,11,55,7,5,11,75,100.0,Placed

In [ ]:
df=pd.read_csv('student_data.csv')
df2=df.loc[df['study_hours']==11,['sleep_hours', 'attendance']]
df2

      sleep_hours  attendance
2               7          60
9               4          77
10              8          64
29              9          63
30              5          45
...           ...         ...
9969            8          84
9971            9          81
9978            8          92
9979            9          78
9988            6          94

[868 rows x 2 columns]

In [ ]:
df=pd.read_csv('student_data.csv')
df2=df.loc[df['assignments_completed']==8].iloc[1]
df2

study_hours                   5
attendance                   52
sleep_hours                   8
internet_usage                6
assignments_completed         8
previous_score               40
exam_score                78.82
placement_status         Placed
Name: 4, dtype: object

**df[condition]**

**df.loc[condition, columns]**

In [ ]:
df=pd.read_csv('student_data.csv')
df[df['assignments_completed']>3]

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.00,Placed
1,4,69,5,3,8,56,100.00,Placed
2,11,60,7,6,10,45,100.00,Placed
3,8,99,9,8,4,55,90.17,Placed
4,5,52,8,6,8,40,78.82,Placed
...,...,...,...,...,...,...,...,...
9995,2,58,9,7,8,88,69.31,Not Placed
9996,7,98,6,9,4,87,100.00,Placed
9997,10,44,8,5,10,37,95.94,Placed
9998,10,75,7,5,8,52,88.61,Placed
9999,2,70,6,11,16,52,78.96,Placed

**To add a new column and data**

In [ ]:
df=pd.read_csv('student_data.csv')
df["age"]=20

df

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status,age
0,7,56,8,7,10,62,100.00,Placed,20
1,4,69,5,3,8,56,100.00,Placed,20
2,11,60,7,6,10,45,100.00,Placed,20
3,8,99,9,8,4,55,90.17,Placed,20
4,5,52,8,6,8,40,78.82,Placed,20
...,...,...,...,...,...,...,...,...,...
9995,2,58,9,7,8,88,69.31,Not Placed,20
9996,7,98,6,9,4,87,100.00,Placed,20
9997,10,44,8,5,10,37,95.94,Placed,20
9998,10,75,7,5,8,52,88.61,Placed,20
9999,2,70,6,11,16,52,78.96,Placed,20

To rename-> rename the col or row and returning a new dataframe so store it anywhere

In [ ]:
df=pd.read_csv('student_data.csv')
df=df.rename(columns={'assignments_completed': 'assign_completed'})
df

,study_hours,attendance,sleep_hours,internet_usage,assign_completed,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.00,Placed
1,4,69,5,3,8,56,100.00,Placed
2,11,60,7,6,10,45,100.00,Placed
3,8,99,9,8,4,55,90.17,Placed
4,5,52,8,6,8,40,78.82,Placed
...,...,...,...,...,...,...,...,...
9995,2,58,9,7,8,88,69.31,Not Placed
9996,7,98,6,9,4,87,100.00,Placed
9997,10,44,8,5,10,37,95.94,Placed
9998,10,75,7,5,8,52,88.61,Placed
9999,2,70,6,11,16,52,78.96,Placed

But if we want to run it in the same df like doesn't want to create copies so use inplace:true

In [ ]:
df=pd.read_csv('student_data.csv')
df.rename(columns={'assignments_completed': 'assign_completed'}, inplace=True)
df

,study_hours,attendance,sleep_hours,internet_usage,assign_completed,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.00,Placed
1,4,69,5,3,8,56,100.00,Placed
2,11,60,7,6,10,45,100.00,Placed
3,8,99,9,8,4,55,90.17,Placed
4,5,52,8,6,8,40,78.82,Placed
...,...,...,...,...,...,...,...,...
9995,2,58,9,7,8,88,69.31,Not Placed
9996,7,98,6,9,4,87,100.00,Placed
9997,10,44,8,5,10,37,95.94,Placed
9998,10,75,7,5,8,52,88.61,Placed
9999,2,70,6,11,16,52,78.96,Placed

The **drop()** function removes things from a DataFrame.

In [ ]:
df.drop('attendance', axis=1 )

,study_hours,sleep_hours,internet_usage,assign_completed,previous_score,exam_score,placement_status
0,7,8,7,10,62,100.00,Placed
1,4,5,3,8,56,100.00,Placed
2,11,7,6,10,45,100.00,Placed
3,8,9,8,4,55,90.17,Placed
4,5,8,6,8,40,78.82,Placed
...,...,...,...,...,...,...,...
9995,2,9,7,8,88,69.31,Not Placed
9996,7,6,9,4,87,100.00,Placed
9997,10,8,5,10,37,95.94,Placed
9998,10,7,5,8,52,88.61,Placed
9999,2,6,11,16,52,78.96,Placed

df.dropna()-> Remove rows that contain missing values (NaN).

In [ ]:
df.dropna()

,study_hours,attendance,sleep_hours,internet_usage,assign_completed,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.00,Placed
1,4,69,5,3,8,56,100.00,Placed
2,11,60,7,6,10,45,100.00,Placed
3,8,99,9,8,4,55,90.17,Placed
4,5,52,8,6,8,40,78.82,Placed
...,...,...,...,...,...,...,...,...
9995,2,58,9,7,8,88,69.31,Not Placed
9996,7,98,6,9,4,87,100.00,Placed
9997,10,44,8,5,10,37,95.94,Placed
9998,10,75,7,5,8,52,88.61,Placed
9999,2,70,6,11,16,52,78.96,Placed

In [ ]:


dct = {
    'name': ['Ton', 'Krish', None, 'Vani'],
    'age': [20, None, 18, 19],
    'roll': [1, 2, 3, 4]
}

df2 = pd.DataFrame(dct)


df2=df2.dropna()
df2

   name   age  roll
0   Ton  20.0     1
3  Vani  19.0     4

In [ ]:
df.sort_values("attendance")

,study_hours,attendance,sleep_hours,internet_usage,assign_completed,previous_score,exam_score,placement_status
34,4,40,8,7,15,59,63.20,Not Placed
6,10,40,4,11,9,50,98.12,Placed
26,6,40,9,2,9,51,95.60,Placed
5,7,40,9,10,0,60,72.33,Placed
32,3,40,8,6,2,85,75.73,Placed
...,...,...,...,...,...,...,...,...
9609,8,100,7,11,10,75,100.00,Placed
431,1,100,9,1,12,88,100.00,Placed
418,5,100,7,11,1,39,80.74,Placed
3571,9,100,5,4,10,86,100.00,Placed
9992,5,100,9,2,9,62,100.00,Placed

**df.sort_index()->** Sort the DataFrame by its index (row labels).

In [ ]:
df.sort_index()

,study_hours,attendance,sleep_hours,internet_usage,assign_completed,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.00,Placed
1,4,69,5,3,8,56,100.00,Placed
2,11,60,7,6,10,45,100.00,Placed
3,8,99,9,8,4,55,90.17,Placed
4,5,52,8,6,8,40,78.82,Placed
...,...,...,...,...,...,...,...,...
9995,2,58,9,7,8,88,69.31,Not Placed
9996,7,98,6,9,4,87,100.00,Placed
9997,10,44,8,5,10,37,95.94,Placed
9998,10,75,7,5,8,52,88.61,Placed
9999,2,70,6,11,16,52,78.96,Placed

**isnull()-> ** Checks whether values are missing and returns a boolean value

In [ ]:
df.isnull()

,study_hours,attendance,sleep_hours,internet_usage,assign_completed,previous_score,exam_score,placement_status
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
9995,False,False,False,False,False,False,False,False
9996,False,False,False,False,False,False,False,False
9997,False,False,False,False,False,False,False,False
9998,False,False,False,False,False,False,False,False
9999,False,False,False,False,False,False,False,False

**notnull()->** Opposite of isnull().

In [ ]:
df.notnull()

,study_hours,attendance,sleep_hours,internet_usage,assign_completed,previous_score,exam_score,placement_status
0,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...
9995,True,True,True,True,True,True,True,True
9996,True,True,True,True,True,True,True,True
9997,True,True,True,True,True,True,True,True
9998,True,True,True,True,True,True,True,True
9999,True,True,True,True,True,True,True,True

In [ ]:
dct = {
    'name': ['Ton', 'Krish', None, 'Vani'],
    'age': [20, None, 18, 19],
    'roll': [1, 2, 3, 4]
}

df3 = pd.DataFrame(dct)

df3.notnull()

    name    age  roll
0   True   True  True
1   True  False  True
2  False   True  True
3   True   True  True

In [ ]:
dct = {
    'name': ['Ton', 'Krish', None, 'Vani'],
    'age': [20, None, 18, 19],
    'roll': [1, 2, 3, 4]
}

df3 = pd.DataFrame(dct)

df3.isnull()

    name    age   roll
0  False  False  False
1  False   True  False
2   True  False  False
3  False  False  False

**fillna(n)->** Instead of removing missing values, replace them.

In [ ]:

dct = {
    'name': ['Ton', 'Krish', None, 'Vani'],
    'age': [20, None, 18, 19],
    'roll': [1, 2, 3, 4]
}

df3 = pd.DataFrame(dct)


df3.fillna(2)

    name    age  roll
0   True   True  True
1   True  False  True
2  False   True  True
3   True   True  True

**df['column_name'].unique()->**  Show all distinct (non-repeated) values in a column.

In [ ]:
df['attendance'].unique()

array([ 56,  69,  60,  99,  52,  40,  86,  72,  77,  64,  65,  98,  67,
        76,  80,  96,  88,  87,  47,  95,  51,  44,  63,  45,  71,  81,
        42,  58,  82,  68,  89,  41,  48,  85,  75, 100,  59,  43,  54,
        55,  50,  94,  93,  73,  61,  90,  66,  49,  97,  70,  84,  74,
        92,  46,  91,  83,  79,  78,  57,  62,  53])